config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  "/"  => "top#index"

  resources :pets
  resources :posts
  post '/posts/:id/comment' => 'posts#create_comment'
  resources :tasks
  post '/tasks/:id/complete' => 'tasks#complete'

  get "/calendar" => "calendar#index"
  get "/search" => "search#index"
end
 

app/models/Post.rb
class Post < ApplicationRecord
  belongs_to :pet, optional: true
  belongs_to :user
  has_many :post_comments

  def status_text
    case self.status
    when 1 then
      return '下書き'
    when 2 then
      return '公開'
    when 3 then
      return '非公開'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :pet_type

  def gender_text
    case self.gender
    when 1 then
      return 'オス'
    when 2 then
      return 'メス'
    when 3 then
      return '不明'
    end
  end
end

app/models/pet_type.rb
class PetType < ApplicationRecord
  #has_many :pets 
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #deviseコントローラーにストロングパラメータと追加する
  #before_action :configure_permitted_parameters, if: devise_controller?

  protected
  def configure_permitted_parameters
  #サインアップ時にnameのストロングパラメータを追加する
    devise_parameter_sanitizer.permit(:sing_up, key: [:name])
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @pets = Pet.where(user_id: current_user.id)
    pet_id = params[:pet_id]
    posts = Post.where(user_id: current_user.id).where(pet_id: pet_id).where(status: 2)
    @events = []
    posts.each do |post|
      @events.push({
        title: post.title,
        date: post.created_at.strftime("%Y-%m-%d"),
        url: post_path(post.id),
      })
    end
    if pet_id.present?
      pet = Pet.find(pet_id)
      @events.push({
        title: "#{pet.name}の誕生日",
        date: pet.birthday.strftime("%Y-%m-%d"),
        url:pet_path(pet.id),
      })  
      else
      tasks = Task.where(user_id: current_user.id)
      tasks.each do |task| 
        @events.push({
          title: task.name,
          date: task.plan_date.strftime("%Y-%m-%d"),
          url: task_path(task.id),
      })
      end
    end
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.where(user_id: current_user.id)
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new()
    @pet_types = PetType.all
  end

  def create
    p = params.permit(
      :name,
      :pet_type_id,
      :gender,
      :birthday,
      :memo
    )
    p[:user_id] = current_user.id
    Pet.create(p)
    flash[:success] = 'ペットを登録しました！'
    redirect_to pets_path()
  end

  def edit
    @pet = Pet.find(params[:id])
    @pet_types = PetType.all
  end

  def update
    @pet = Pet.find(params[:id])
    p = params.permit(
      :name,
      :pet_type_id,
      :gender,
      :birthday,
      :memo
    )
    @pet.assign_attributes(p)
    @pet.save
    flash[:success] = 'ペットを情報を変更しました！'
    redirect_to pets_path()
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new()
    @pets = Pet.where(user_id: current_user.id)
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    p = params.permit(
    :title,
    :content,
    :status,
    :pet_id
    )
    p[:user_id] = current_user.id
    Post.create!(p)
    flash[:success] = '日記を保存しました！'
    redirect_to "/calendar"
  end

  def create_comment
    p = params.permit(
      :content,
    )
    p[:user_id] = current_user.id
    p[:post_id] = params[:id]
    PostComment.create(p)
    flash[:success] = 'コメントを投稿しました！'
    redirect_to post_url(params[:id]) 
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @keyword = params[:q]
    @posts = Post.where(status: 2)

    if @keyword.present?
      @posts = @posts
        .where('title like ?', "%#{@keyword}%")
        .or(
          Post.where(status:2)
        .where('content like ?', "%#{@keyword}%")
        )
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #一覧ページ
  def index
    @tasks = Task
    .where(user_id: current_user.id)
    .order('plan_date asc')
  end

  def show
    @task = Task.find(params[:id])
  end

  #登録フォームのページ
  def new
    @task = Task.new()
  end

  #登録処理
  def create
    p = params.permit(
      :name,
      :plan_date,
      :memo
    )
    p[:user_id] = current_user.id
    p[:is_completed] = 0
    Task.create(p)
    flash[:success] = 'タスクを登録しました！'
    redirect_to tasks_path()
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    p = params.permit(
      :name,
      :plan_date,
      :memo
    )
    @task.assign_attributes(p)
    @task.save
    flash[:success] = 'タスク情報を変更しました！'
    redirect_to tasks_path()
  end

  def complete
    @task = Task.find(params[:id])
    @task.is_completed = 1
    @task.save
    flash[:success] = 'タスクを完了しました！'
    redirect_to tasks_path()
  end
end
   

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in?
      redirect_to "/calendar"
    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/calendar/index.html.erb
<form method="get" action="/calendar" id="calendar-form">
  <div class="mb-3">
    <label for="pet_id">カレンダーの種類</label>
    <select name="pet_id" class="f orm-select" id="pet_id">
      <option value="">選択なし</option>
      <% @pets.each do |pet| %>
        <option value="<%= pet.id %>" <%= 'selected' if pet.id.to_s == params[:pet_id] %>><%= pet.name %></option>
      <% end %>
    </select>
  </div>
</form>
<%= month_calendar do |date| %>
  <%= date.strftime("%d") %>
  <br>
  <% @events.each do |event| %>
    <% if event[:date] == date.strftime("%Y-%m-%d") %>
      <a href="<%= event[:url] %>"><%= event[:title] %></a><br>
    <% end %>
    <% end %>
  <% end %>
 
<script>
  $('#pet_id').on('change' , function() {
      $('#calendar-form').submit();
  });
</script>

app/views/mypage/index.html.erb
<p><%= current_user.name %></p>
<p>twitter機能みたいな</p>

app/views/pets/edit.html.erb
<h2>ペット情報編集</h2>

<%= form_with model: @pet do |form| %>
  <div class="mb-3 mb-5">
     <label for="name">なまえ</label>
    <input name="name" type="text" class="form-control" id="name" placeholder="なまえを入力してください" value="<%= @pet.name %>">
  </div>
  <div class="mb-3">
    <label for="pet_type_id">種類</label>
    <select name="pet_type_id" class="form-select" id="pet_type_id" value="<%= @pet_type_id %>">
      <% @pet_types.each do |pet_type| %>
        <option value="<%= pet_type.id %>" <%= 'selected' if pet_type.id == @pet.pet_type_id %>><%= pet_type.name %></option>
        <% end %>
    </select>
  </div>
  <!--<input name="create_at" value="aaa" />-->
  <div class="mb-3">
    <label for="gender">性別</label>
      <div class="form-check">
        <input class="form-check-input" value="1" type="radio" name="gender" id="gender-1" value="<%= 'checked' if @pet.gender == 1 %>">
        <label class="form-check-label" for="gender-1">
        オス
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" value="2" type="radio" name="gender" id="gender-2" value="<%= 'checked' if @pet.gender == 2 %>">
        <label class="form-check-label" for="gender-2">
        メス
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" value="3" type="radio" name="gender" id="gender-3" value="<%= 'checked' if @pet.gender == 3 %>">
        <label class="form-check-label" for="gender-3">
        不明
        </label>
      </div>
  </div>
    <div class="mb-3">
     <label for="birthday">誕生日</label>
    <input name="birthday" type="date" class="form-control" id="birthday" placeholder="誕生日を入力してください" value="<%= @pet.birthday.strftime("%Y-%m-%d") %>">
  </div>

  <div class="mb-3">
    <label for="memo">メモ</label>
    <textarea name="memo" class="form-control" id="memo" rows="3">
      <%= @pet.memo %>
    </textarea>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/pets/index.html.erb
<h2>ペット一覧</h2>

<div class="row">
  <div class="col-9">
  </div>
  <div class="col-3">
    <a href="/pets/new">ペット情報追加</a>
  </div>
</div>

<div class="row">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">なまえ</th>
      <th scope="col">種類</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet| %>
    <tr>
      <td><%= pet.name %></td>
      <td><%= pet.pet_type.name %></td>
      <td><a href="<%= pet_path(pet.id) %>">詳細</a></td>
      <td><a href="<%= edit_pet_path(pet.id) %>">編集</a></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/pets/new.html.erb
<h2>ペット情報登録</h2>

<%= form_with model: @pet do |form| %>
  <div class="mb-3 mb-5">
     <label for="name">なまえ</label>
    <input name="name" type="text" class="form-control" id="name" placeholder="なまえを入力してください">
  </div>
  <div class="mb-3">
    <label for="pet_type_id">種類</label>
    <select name="pet_type_id" class="form-select" id="pet_type_id">
      <% @pet_types.each do |pet_type| %>
        <option value="<%= pet_type.id %>"><%= pet_type.name %></option>
        <% end %>
    </select>
  </div>
  <!--<input name="create_at" value="aaa" />-->
  <div class="mb-3">
    <label for="gender">性別</label>
      <div class="form-check">
        <input class="form-check-input" value="1" type="radio" name="gender" id="gender-1">
        <label class="form-check-label" for="gender-1">
        オス
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" value="2" type="radio" name="gender" id="gender-2">
        <label class="form-check-label" for="gender-2">
        メス
        </label>
      </div>
      <div class="form-check">
        <input class="form-check-input" value="3" type="radio" name="gender" id="gender-3">
        <label class="form-check-label" for="gender-3">
        不明
        </label>
      </div>
  </div>
    <div class="mb-3">
     <label for="birthday">誕生日</label>
    <input name="birthday" type="date" class="form-control" id="birthday" placeholder="誕生日を入力してください">
  </div>

  <div class="mb-3">
    <label for="memo">メモ</label>
    <textarea name="memo" class="form-control" id="memo" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/pets/show.html.erb
<h2>ペット情報</h2>

<div class="row">
  <div class="col-3">
    <p>なまえ</p>
  </div>
  <div class="col-9"> 
    <p><%= @pet.name %></p>
  </div>
</div>
<div class="row">
  <div class="col-3">
    <p>種類</p>
  </div>
  <div class="col-9">
    <p><%= @pet.pet_type.name %></p>
  </div>
</div>
<div class="row">
  <div class="col-3">
    <p>性別</p>
  </div>
  <div class="col-9">
    <p><%= @pet.gender_text %></p>    
  </div>
</div>
<div class="row">
  <div class="col-3">
    <p>誕生日</p>
  </div>
  <div class="col-9">
    <p><%= @pet.birthday.strftime("%Y-%m-%d") %></p>    
  </div>
</div>
<div class="row">
  <div class="col-3">
    <p>メモ</p>
  </div>
  <div class="col-9">
    <p><%= @pet.memo %></p>    
  </div>
</div>

app/views/posts/new.html.erb
<h2>日記を書く</h2>

<%= form_with model: @post do |form| %>

  <div class="mb-3 mb-5">
    <label for="title">タイトル</label>
    <input name="title" type="text" class="form-control" id="title" placeholder="タイトルを入力してください">
  </div>
  <div class="mb-3">
    <label for="content">内容</label>
    <textarea name="content" class="form-control" id="content" rows="3"></textarea>
  </div>
  <div class="mb-3">
    <label for="status">ステータス</label>
    <select name="status" class="form-select" id="status">
      <option value="1">下書き</option>  
      <option value="2">公開</option>
      <option value="3">非公開</option>
    </select>
  </div>
  <div class="mb-3">
    <label for="pet_id">ペット</label>
    <select name="pet_id" class="form-select" id="pet_id">
      <option>選択なし</option>
      <% @pets.each do |pet| %>
        <option value="<%= pet.id %>"><%= pet.name %></option>
        <% end %>
    </select>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/posts/show.html.erb
<div style="margin: 10px 40px;">
  <h2><%= @post.title %></h2>
  <div class="mb-0 d-flex justify-content-start align-items-center">
    <p><%= @post.created_at.strftime("%Y-%m-%d") %></p>
    <p class="ml-3"><span class="badge bg-success"><%= @post.status_text() %></span></p>
  </div>
  <div class="d-flex justify-content-start align-items-center">
    <p>ユーザー：<%= @post.user.name %></p>
    <% if @post.pet.present? %>
      <p class="ml-3"><span class="badge bg-success"><%= @post.pet.name %></span></p>
    <% end %>
  </div>

  <p class="mt-5 mb-5">
  <%= @post.content.gsub(/\n/,'<br>').html_safe %>
  </p>

  <% @post.post_comments.each do |post_comment| %>
    <p class="mb-0 fw-bold"><%= post_comment.user.name %></p>
    <p><%= post_comment.content.gsub(/\n/,'<br>').html_safe %></p>
    <hr>
  <% end %>

  <% if user_signed_in? %>
  <h5>コメントを書く</h5>
  <%= form_with url: "/posts/#{@post.id}/comment", method: 'post' do |form| %>
    <div class="form-group mb-3">
      <textarea class="form-control" id="comment" name="content" rows="3"></textarea>
    </div>
      <button type="submit" class="btn btn-primary">投稿</button>
  <% end %>
  <% end %>
</div>

app/views/search/index.html.erb
<% if @keyword.present? %>
  <h2>「<%= @keyword %>」の検索結果</h2>
<% else %>
  <h2>全ての日記</h2>
<% end %>

<div class="d-flex justify-content-start" style="flex-wrap: wrap; gap: 20px;">
<% @posts.each do |post| %>
  <div class="card" style="width: 200px;">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <% if post.pet.present? %>
        <h6 class="card-subtitle mb-2 text-muted"><%= post.pet.name %></h6>
      <% end %>
      <p class="card-text"><%= post.content.slice(0, 20) %>...</p>
      <a href="<%= post_path(post.id) %>" class="card-link">続きを見る</a>
    </div>
  </div>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h2>タスク情報編集</h2>

<%= form_with model: @task do |form| %>
  <div class="mb-3 mb-5">
     <label for="name">やること</label>
    <input name="name" type="text" class="form-control" id="name" placeholder="やることを入力してください" value="<%= @task.name %>">
  </div>
  <div class="mb-3">
     <label for="plan_date">期日</label>
    <input name="plan_date" type="date" class="form-control" id="plan_date" placeholder="期日を入力してください" value="<%= @task.plan_date.strftime("%Y-%m-%d") %>">
  </div>

  <div class="mb-3">
    <label for="memo">メモ</label>
    <textarea name="memo" class="form-control" id="memo" rows="3"><%= @task.memo %></textarea>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/tasks/index.html.erb
<h2>タスク一覧</h2>

<div class="row">
  <div class="col-9">
  </div>
  <div class="col-3">
    <a href="/tasks/new">タスク情報追加</a>
  </div>
</div>

<div class="row">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">やること</th>
      <th scope="col">期日</th>
      <th scope="col">状況</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
    <tr>
      <td><%= task.name %></td>
      <td><%= task.plan_date.strftime("%Y-%m-%d") %></td>
      <td>
        <% if task.is_completed == 1 %>
          完了済み
        <% else %>
          <%= form_with url: "/tasks/#{task.id}/complete", method: 'post' do |form| %>
            <button type="submit">完了にする</button>
          <% end %>
        <% end %>
      </td>
       <td><a href="<%= task_path(task.id) %>">詳細</a></td>
       <td><a href="<%= edit_task_path(task.id) %>">編集</a></td>
    </th>
    <% end %>
  </tbody>
</table>
</div>

app/views/tasks/new.html.erb
<h2>タスク情報登録</h2>

<%= form_with model: @task do |form| %>
  <div class="mb-3 mb-5">
     <label for="name">やること</label>
    <input name="name" type="text" class="form-control" id="name" placeholder="やることを入力してください">
  </div>

  <div class="mb-3">
     <label for="plan_date">期日</label>
    <input name="plan_date" type="date" class="form-control" id="plan_date" placeholder="期日を入力してください">
  </div>

  <div class="mb-3">
    <label for="memo">メモ</label>
    <textarea name="memo" class="form-control" id="memo" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary">保存</button>
<% end %>

app/views/tasks/show.html.erb
<h2>タスク情報</h2>

<div class="row">
  <div class="col-3">
    <p>やること</p>
  </div>
  <div class="col-9">
    <p><%= @task.name %></p>
  </div>
</div>
<div class="row">
  <div class="col-3">
    <p>期日</p>
  </div>
  <div class="col-9">
    <p><%= @task.plan_date.strftime("%Y-%m-%d") %></p>
  </div>
</div>
<div class="row">
  <div class="col-3">
    <p>メモ</p>
  </div>
  <div class="col-9">
    <p><%= @task.memo %></p>
  </div>
</div>
  

app/views/top/index.html.erb
<br><br>
<p>げっ歯類に特化したペットのお世話内容、健康管理をシンプルに記録と確認することができます！<br>
また関連するペットの検索機能を使い、データで体調管理を簡単記録！<br>
カレンダー上からスケジュールの編集、大切な家族との生活や思い出を記録できます。<br>
ペットプロフィールの設置してなまえや誕生日、かかりつけ医などペットごとに設定可能！<br><br>
<img src="/assets/itoshigotop.png" width="80%" height="40%"><br><br>

・ペット登録<br>
複数のペットを登録可能なので多頭飼いもカレンダー毎に管理できます。<br>
<img src="/assets/itoshigolist.png" width="80%" height="40%"><br><br>

・日記機能<br>
日々のお世話の様子を入力、編集、削除など簡単操作！<br>
メモ欄もあるので体重、体調、環境、ご飯、日記、健康チェック、支出管理など合わせてお使いください。<br>
<img src="/assets/itoshigodaily.png" width="80%" height="40%"><br><br>

・タスク機能<br>
用途に合わせたタスクを作成できます。<br>
項目は自由に作成でき、トップ画面に記録が出るので確認も簡単！<br>
<img src="/assets/itoshigotask.png" width="80%" height="40%"><br><br></p>