config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get  "/"  => "top#index"

  resources :pets
  resources :posts
  post '/posts/:id/comment' => 'posts#create_comment'
  resources :tasks
  post '/tasks/:id/complete' => 'tasks#complete'

  get "/calendar" => "calendar#index"
  get "/search" => "search#index"
end
 

app/models/Post.rb
class Post < ApplicationRecord
  belongs_to :pet, optional: true
  belongs_to :user
  has_many :post_comments

  def status_text
    case self.status
    when 1 then
      return '下書き'
    when 2 then
      return '公開'
    when 3 then
      return '非公開'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :pet_type

  def gender_text
    case self.gender
    when 1 then
      return 'オス'
    when 2 then
      return 'メス'
    when 3 then
      return '不明'
    end
  end
end

app/models/pet_type.rb
class PetType < ApplicationRecord
  #has_many :pets 
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  def index
    @pets = Pet.where(user_id: current_user.id)
    pet_id = params[:pet_id]
    posts = Post.where(user_id: current_user.id).where(pet_id: pet_id).where(status: 2)
    @events = []
    posts.each do |post|
      @events.push({
        title: post.title,
        date: post.created_at.strftime("%Y-%m-%d"),
        url: post_path(post.id),
      })
    end
    if pet_id.present?
      pet = Pet.find(pet_id)
      @events.push({
        title: "#{pet.name}の誕生日",
        date: pet.birthday.strftime("%Y-%m-%d"),
        url:pet_path(pet.id),
      })  
      else
      tasks = Task.where(user_id: current_user.id)
      tasks.each do |task| 
        @events.push({
          title: task.name,
          date: task.plan_date.strftime("%Y-%m-%d"),
          url: task_path(task.id),
      })
      end
    end
  end
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def index
  
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
    @pets = Pet.where(user_id: current_user.id)
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def new
    @pet = Pet.new()
    @pet_types = PetType.all
  end

  def create
    p = params.permit(
      :name,
      :pet_type_id,
      :gender,
      :birthday,
      :memo
    )
    p[:user_id] = current_user.id
    Pet.create(p)
    flash[:success] = 'ペットを登録しました！'
    redirect_to pets_path()
  end

  def edit
    @pet = Pet.find(params[:id])
    @pet_types = PetType.all
  end

  def update
    @pet = Pet.find(params[:id])
    p = params.permit(
      :name,
      :pet_type_id,
      :gender,
      :birthday,
      :memo
    )
    @pet.assign_attributes(p)
    @pet.save
    flash[:success] = 'ペットを情報を変更しました！'
    redirect_to pets_path()
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new()
    @pets = Pet.where(user_id: current_user.id)
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    p = params.permit(
    :title,
    :content,
    :status,
    :pet_id
    )
    p[:user_id] = current_user.id
    Post.create!(p)
    flash[:success] = '日記を保存しました！'
    redirect_to "/calendar"
  end

  def create_comment
    p = params.permit(
      :content,
    )
    p[:user_id] = current_user.id
    p[:post_id] = params[:id]
    PostComment.create(p)
    flash[:success] = 'コメントを投稿しました！'
    redirect_to post_url(params[:id]) 
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @keyword = params[:q]
    @posts = Post.where(status: 2)

    if @keyword.present?
      @posts = @posts
        .where('title like ?', "%#{@keyword}%")
        .or(
          Post.where(status:2)
        .where('content like ?', "%#{@keyword}%")
        )
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  #一覧ページ
  def index
    @tasks = Task
    .where(user_id: current_user.id)
    .order('plan_date asc')
  end

  def show
    @task = Task.find(params[:id])
  end

  #登録フォームのページ
  def new
    @task = Task.new()
  end

  #登録処理
  def create
    p = params.permit(
      :name,
      :plan_date,
      :memo
    )
    p[:user_id] = current_user.id
    p[:is_completed] = 0
    Task.create(p)
    flash[:success] = 'タスクを登録しました！'
    redirect_to tasks_path()
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    p = params.permit(
      :name,
      :plan_date,
      :memo
    )
    @task.assign_attributes(p)
    @task.save
    flash[:success] = 'タスク情報を変更しました！'
    redirect_to tasks_path()
  end

  def complete
    @task = Task.find(params[:id])
    @task.is_completed = 1
    @task.save
    flash[:success] = 'タスクを完了しました！'
    redirect_to tasks_path()
  end
end
   

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    if user_signed_in?
      redirect_to "/calendar"
    else
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!--topを編集するページ-->
<!DOCTYPE html>
<html>
  <head>
    <title>itoshigo</title>
    <!--<a href="index.html" title="このカテゴリーのトップへジャンプします">カテゴリートップ</a>-->
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <script
  src="https://code.jquery.com/jquery-3.6.1.min.js"
  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
  crossorigin="anonymous"></script>
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  </head>

  <body>
    <!-- 全体 -->
    <div class="container">
    <!-- 画像表示
    <img src="/assets/main.JPG">-->
      <!-- header -->
      <div class="d-flex justify-content-between align-items-center">
        <!-- logo -->
        <h1 class="logo"><a href="/">itoshigo</a></h1>
        <!-- searchbox -->
        <div class="d-flex justify-content-center">
          <form method="get" action="/search" class="d-flex" style="width: 400px; height: 35px;">
            <input type="text" name="q" class="flex-grow-1">
            <button type="submit" class="btn">検索</button>
         </form>
        </div>
      </div>

    <div class="row">
    <% if user_signed_in? %>
      <div class="col-2">
        <ul>
          <li><a href="<%= pets_path() %>">ペット一覧</a></li>
          <li><a href="<%= new_post_path() %>">日記を書く</a></li>
          <li><a href="<%= calendar_path() %>">カレンダー</a></li>
          <li><a href="<%= tasks_path() %>">タスクリスト</a></li>
          <li><a href="<%= edit_user_registration_path() %>">ユーザー情報変更</a></li>
          <li><%= link_to('ログアウト',
            destroy_user_session_path(),
            method: :delete)
            %></li>
        </ul>
      </div>
      <% else %>
        <div class="col-2">
        <ul>
          <li><a href="/users/sign_up">会員登録</a></li>
          <li><a href="/users/sign_in">ログイン</a></li>
        </ul>
        </div>
       <% end %>
      <div class="col">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-info" role="alert">
            <%= message %>
          </div>
        <% end %>
      <%= yield %>
      </div>
      <div class="footer">
        <a href="http://localhost:3000/"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-map" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M15.817.113A.5.5 0 0 1 16 .5v14a.5.5 0 0 1-.402.49l-5 1a.502.502 0 0 1-.196 0L5.5 15.01l-4.902.98A.5.5 0 0 1 0 15.5v-14a.5.5 0 0 1 .402-.49l5-1a.5.5 0 0 1 .196 0L10.5.99l4.902-.98a.5.5 0 0 1 .415.103zM10 1.91l-4-.8v12.98l4 .8V1.91zm1 12.98 4-.8V1.11l-4 .8v12.98zm-6-.8V1.11l-4 .8v12.98l4-.8z"/></svg></a>

        <a href="https://github.co.jp/"><svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/></svg></a>
        <p>&copy; itoshigo</p>
      </div>
    </div>
    </div>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: '←前の月'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: '次の月→'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: "#{calendar.td_classes_for(day)} calendar-date-box", style: 'width: 10%; height: 80px;' do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>